### ISSUE TITLE
Support for extended tweets longer than 140 characters

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gateplugin-Format_Twitter#2]
At the moment we only parse the top level `text` and `entities` from tweet JSON, in the case of long tweets over 140 characters this is the truncated text, with the full text and corresponding entities found under `extended_tweet`.

**Comment by ianroberts** [comment]
For retweets this is even worse - here the top-level object doesn't have an `extended_tweet` with the full text at all, only the `text` field with the truncated original text prefixed `RT @blah`.  To get the full text you have to dive into `retweeted_status`/`extended_tweet`.

The current format is fully round-trippable, we need to think carefully about how (or whether?) we maintain that when the format parser may have pulled the text from one of several different places in the original JSON.

**Comment by greenwoodma** [comment]
fixed by 2e792da0d098d2740bd4af5a915945010a8b04fc and a few preceding commits
