### ISSUE TITLE
Work out how to support quoted tweets

### ISSUE THREAD

**Issue by ianroberts** [GateNLP/gateplugin-Format_Twitter#3]
For a "quote" tweet, the top-level `text` property is just the quoter's comment, it doesn't include the text of the tweet they are quoting or any associated entities (which are all inside the `quoted_status`).  We need to consider carefully how we want to represent this sort of thing in GATE, particularly with regard to how (or if?) we are able to round-trip such documents into GATE and back out to JSON.

**Comment by greenwoodma** [comment]
fixed by 2e792da0d098d2740bd4af5a915945010a8b04fc and a few preceding commits
